# Appendix A  Status of Structures Assessed in the Field {-}

## Non-Actionable Barriers
No barriers were identified as non-actionable through the implementation of this WCRP as of May 2026.


## Data-deficient Barriers {-}

```{r table5, echo = FALSE, results = 'asis'}
#| label: table-5
#| tbl-cap: "Table 5: Structures in the Tuzist’ol T’ah watersheds that have been assessed for fish passage for Talo as of May 2026, but either require an additional in-depth fish-passage assessment to confirm the passability status or a habitat assessment to confirm upstream habitat values."
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/tables(tbl-data-deficient-sk).csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```

```{r table6, echo = FALSE, results = 'asis'}
#| label: table-6
#| tbl-cap: "Table 6: Structures in the Tuzist’ol T’ah watersheds that have been assessed for fish passage for Chinook Salmon as of May 2026, but either require an additional in-depth fish-passage assessment to confirm the passability status or a habitat assessment to confirm upstream habitat values."
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/tables(tbl-data-deficient-ch).csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```

## Excluded Structures {-}

```{r table7, echo = FALSE, results = 'asis'}
#| label: table-7
#| tbl-cap: "Table 7: Structures in the Tuzist'ol T'ah watersheds that are excluded from further consideration in subsequent ranking and work planning because the structure is not present, is confirmed passable (e.g., bridge), or has no habitat upstream for Talo or Chinook Salmon."
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/table5(tbl-excluded).csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```
