

# Methods {-}
Connectivity models were produced using NSFishPass, an open-source freshwater connectivity modelling framework, which combines provincial spatial layers with WCRP-specific data tables and includes two sub-models: 

## Accessibility Model {-}
Naturally accessible waterbodies are those that would likely be accessible to focal species if no human-made barriers existed on the landscape. This is treated as a proxy baseline for the historic distribution. Naturally accessible waterbodies were identified based on natural barriers (i.e., waterfalls or steep stream gradients) that would naturally limit upstream movement. Modelled natural barriers were excluded if focal species observations existed upstream of them. For Atlantic Salmon, accessibility limits were defined by >5 m waterfalls or >30% channel gradients. For American Eel, all rivers were considered accessible. 


## Habitat Model {-}
A subset of the naturally accessible waterbody layer that is defined as key habitat (e.g., habitat likely to support spawning or rearing) (henceforth habitat), rather than simply being used as a movement corridor. An intrinsic potential modelling approach was used to identify areas that have the potential to support spawning or rearing for Atlantic Salmon based on stream characteristics such as gradient and discharge. For American Eel, habitat was identified by removing first-order streams from the accessible waterbody layer, recognizing that these streams typically have low habitat value for these species. Habitat model outputs were overruled by field data and local knowledge of habitat condition and use.  


## Connectivity Modelling {-}
The overall model used to estimate connectivity status and rank structures. A layer of known or modelled structures was overlaid on the habitat model output. Modelled stream crossings were created from stream network and road/railway Geographic Information System (GIS) data, by mapping where a road or railway crosses a stream. Dam data were obtained from the Canadian Aquatic Barriers Database (aquaticbarriers.ca). All mapped dams and modelled crossings (henceforth structures) downstream of habitat were considered, but some were classified as non-existent or passable prior to initiating field work and excluded from the model. Stream crossings on 6th order and larger streams were assumed to be bridges and classified as passable, as were those identified as bridges in available infrastructure spatial layers. Remaining structures downstream of habitat were checked on Google Earth to exclude structures if it could be visibly confirmed that they did not exist or were bridges or cross-ditches. Data from previous field assessments were incorporated, and structures identified as passable were excluded. Assessed barriers, dams lacking fishways, and unassessed structures were all treated as barriers in the connectivity model. If barriers were presumed to be partially passable, the degree of passability was estimated (25%, 50%, or 75%), and the amount of habitat upstream of that barrier was downweighted according to the passability of all downstream barriers. For example, a 10-km habitat patch with two downstream partial barriers (both with 50% passability) would represent 2.5 km of weighted habitat.  

Local knowledge and data were incorporated into model development in two phases and typically overruled modelled outputs where the two differed. Existing reports on habitat, barriers, and fish distributions, when available, were incorporated into the initial model outputs. Maps of initial outputs were then shared with local knowledge holders, who identified model errors or omissions (e.g., unmapped structures, mapped structures that do not exist, known spawning or rearing habitat that was not identified by the model, habitat identified by the model that is known to be inaccessible or unsuitable). The status of closed-bottom structures identified as passable by local knowledge may not have been adjusted until confirmed by field assessments.  

Models were run to produce initial connectivity outputs, and maps were created showing disconnected habitat and associated structures. For diadromous species (both Atlantic Salmon and American Eel), connectivity status was estimated by calculating the proportion of habitat that is connected to the ocean (i.e., not fragmented by human-made barriers). Habitat with no structures or only passable structures downstream was considered connected. Habitat amount was calculated in linear kilometers downweighted according to the passability of all downstream barriers and by stream order, with first-order streams downweighted by 75%, and second-order streams downweighted by 25%. 


## Structure Ranking {-}

Structures were ranked by the amount of weighted habitat upstream, with the highest ranked structure given a rank of 1. Unassessed structures were considered barriers for ranking purposes. Ranks generally represent the relative amount of habitat upstream. Actual ranking processes are more complex to account for situations where multiple barriers may need to be addressed to reconnect habitat. Barriers with the most habitat upstream may not provide any benefits to focal species until downstream barriers are addressed.  

To manage this, both the overall habitat upstream, and immediate gains (i.e., the amount of habitat to the next structure) are incorporated into the ranking process. This ensures that the first structure encountered by fish is given a high rank, even if, for example, it only blocks only 1 km of habitat. Conversely, a structure blocking 20 km of habitat may be given a lower rank if many downstream structures must be addressed before those gains can be realized.  

Structures are also combined into sets by considering which configuration of groups of up to five structures provides the greatest per-barrier habitat gain. Sets are often identified sequentially by first identifying optimal downstream set configurations, then considering additional upstream sets.  

Stream order is also factored into the ranking process, to avoid overvaluing structures where most of the upstream habitat comprises small streams with more limited habitat value. First-order streams are downweighted by 75%, and second-order streams are downweighted by 25%. 

