# Progress Reporting {-}

## Progress Reporting {-}

This WCRP was initiated in 2025 as part of the larger Tuzist’ol T’ah conservation initiative. Since then, several scoping and planning workshops were held with the Tuzist’ol T’ah team, and three in-community (Binche Whu’ten, Nakazdli Whu’ten, Takla Nation) tributary-by-tributary review workshops were held to gather local knowledge and traditional knowledge to refine the preliminary connectivity models. The passability status of 48 structures was assessed in the field and field results reviewed with the Tuzist’ol T’ah team to determine next steps for identified barriers.  


## Rehabilitated Barriers {-}

Barriers that have been rehabilitated will appear in this section, once priority barriers have been actioned and passage restored. 


## Annual Progress Report {-}

Since March 2025 the following actions were completed: 

- Three in-community (Binche Whu’ten, Nakazdli Whu’ten, Takla Nation) tributary-by-tributary review sessions were held in May 2025 to gather local knowledge and inform model updates, resulting in: 
    40 previously unmapped features added to the initial model, 
    30 modelled features confirmed as barriers to fish passage, and 
    30 sites where modelled habitat was modified (either removed or added). 

- Barrier assessments were completed for 48 structures, resulting in: 
    21 structures confirmed as barriers, eighteen of which require additional assessments (i.e., either in-depth passage or habitat confirmation).
    27 structures excluded as passable or non-existent, or because there was no habitat upstream; two of which were confirmed as passable but have maintenance issues of note.  

- The field results were reviewed with the Tuzist’ol T’ah planning team and decisions made on next steps for structures confirmed as barriers; and 

- Connectivity models were updated based on the above actions, and outputs were incorporated into this WCRP. 