
# Acknowledgements and References {-}

## Recommended Citation 

S. Sra, N. Mazany-Wright, F. Montgomery, B. Rebellato, and N. W. R. Lapointe. 2026. Tuzist’ol T’ah watershed connectivity restoration plan. Canadian Wildlife Federation. Ottawa, Ontario, Canada. 


## Acknowledgements {-}

The Canadian Wildlife Federation recognizes that the lands and waters (keyohs) that form the basis of this plan are the traditional unceded territory of the Dakelh people, including the Takla Nation, Yekooche First Nation, Tl’azt’en Nation, Nak’azdli Whut’en, and Binche Whut’en. Plan development and implementation was funded by British Columbia Salmon Restoration and Innovation Fund. Members of the working group (Appendix B) are passionate about the conservation and restoration of freshwater ecosystems and the species they support, and contributed feedback, guidance, and knowledge. Model outputs were further refined based on feedback provided by local knowledge holders beyond the planning team. Accessibility models were inspired by fish-passage prioritization approaches developed by British Columbia’s Fish Passage Technical Working Group.  


## References {-}

Anonymous. 2025. Watershed profiles for Early Stuart Sockeye. Unpublished data provided to Canadian Wildlife Federation by T. Ridley, Fisheries and Oceans Canada. 

Bradford, M.J. and D.C. Braun. 2021. Regional and local effects drive changes in spawning stream occupancy in a sockeye salmon metapopulation.  Canadian Journal of Fisheries and Aquatic Sciences. Volume 78, Number 8. 

[Tuzist’ol T’ah] Binche Whut’en, Government of British Columbia, Fisheries and Oceans Canada, Nak’azdli Whut’en, Takla Nation, Tl’azt’en Nation, Upper Fraser Fisheries Conservation Alliance, and Yekooche First Nation. 2026. 'Ugi bayoh nawhenidle’ | A return to the smokehouse: Tuzist’ol T’ah – Let’s work together; everything is connected. Recovery strategy for Talo. Draft plan. Last updated: March 2, 2026. 

 [DFO] Fisheries and Oceans Canada Department of Fisheries and Oceans. 2025. Spotlight on the Early Stuart Sockeye (Talo) collaborative salmon rebuilding process. Pacific Salmon Strategy Initiative Featured Stories. Available: https://www.dfo-mpo.gc.ca/campaign-campagne/pss-ssp/stories-articles/2025-stuart-sockeye-collab-saumon-rouge-eng.html [Accessed May 20, 2026]. 

Levy Research Services Ltd. and Ecofor Consulting Inc. 2024. Wild salmon policy habitat & ecosystem status report for early Stuart sockeye salmon. Prepared for Fisheries and Oceans Canada, Kamloops, B.C.  

Shas-Ti Environmental LP. 2026. Stuart/Takla fish passage assessments 2025 summary report – final. Prepared for Canadian Wildlife Federation by Shas-Ti Environmental LP, Fort St. James, B.C.  

West, K. and A. Wakelin. 2024. Tuzist’ol T’ah Talo (early Stuart sockeye) revitalization & stewardship planning process. Presented to Visions conference by Takla Nation and Fisheries and Oceans Canada. Available: https://frasersalmon.org/wp-content/uploads/2024/11/2024-Visions-Day-2-Item-4-Early-Stuart-Process.pdf [accessed May 20, 2026]. 

Yekooche First Nation. 2024. Tuzist’ol T’ah Let’s work together: healthy waters & ecosystems: Talo/Early Stuart Sockeye – everything is connected. ESS June 2024 newsletter. Available: https://yekooche.com/wp-content/uploads/2024/06/ESS-Newsletter-June.pdf [Accessed May 20, 2026]. 