# Work Planning {-}

## Structure Ranking Context {-}

Structures are primarily ranked to inform field-assessment planning. Higher-ranked structures contribute greater potential toward habitat connectivity restoration and are therefore typically higher priorities for field assessment. They also represent key knowledge gaps with potential to significantly affect model results. Estimates of current connectivity status could improve considerably, for instance, if many high-ranking structures are passable or do not have habitat upstream. Habitat accumulation curves support decision making around how many and which structures should be assessed, by showing which structures may only minimally affect connectivity. High-ranked structures with minimal habitat upstream may be located low on these curves, because they must be addressed before benefits can be achieved by addressing lower-ranked barriers with more upstream habitat.

If confirmed as barriers, high-ranking structures are also often priorities for further field assessments to confirm upstream habitat before decisions are made about where fish passage should be rehabilitated.

Once field assessments are completed, management decisions are made for each assessed structure. An assessed structure may be excluded from the model if it is passable or there is no habitat upstream, or it may be listed as a priority barrier for fish-passage rehabilitation. Alternatively, some structures confirmed as barriers may be considered 'non-actionable' because the amount and quality of habitat upstream may be low and the costs of rehabilitation may be high relative to those limited potential benefits.

Model ranks provide only limited information on the relative value of rehabilitation among priority barriers. Ranks convey only the relative amount of habitat upstream and do not represent other factors relevant to restoration prioritization, such as habitat quality, cost, social priorities, or logistical constraints and opportunities. Deciding which priority barriers to address first is a social decision-making process that is only partially informed by model outputs. Model outputs also provide broader context about how many structures exist in the system, how many have been identified as priority barriers, and how much habitat is upstream of each relative to others.


## Workplan {-}

The 2026-2027 work plan is currently being developed in collaboration with the planning team. This section will be updated once the work plan has been finalized.

## Priority Barriers {-}

```{r workplan, echo = FALSE, results = 'asis'}
#| label: table-3
#| tbl-cap: "Table 3. Structures in the Lower Trembleur, Upper Trembleur, Middle River, Takla Lake, Driftwood River, and Stuart Lake watershed groups that are confirmed as barriers to fish passage for Talo and Chinook Salmon with confirmed habitat upstream, as of May 2026. Barriers known to be partially passable are indicated by 'yes', with further details provided in the adjacent column. Habitat gain represents the amount (km) of habitat upstream of that barrier to the next structure that will be reconnected for Talo or Chinook Salmon if that barrier is addressed. The number of structures in a set represents the number of structures that must be addressed concurrently to maximize habitat connectivity."
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/table3(tbl-priority-ch).csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```
